/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#86948a",
        "on-error": "#690005",
        "on-tertiary": "#263143",
        "primary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#d8e3fb",
        "surface-tint": "#4edea3",
        "primary-fixed": "#6ffbbe",
        "secondary-container": "#3f465c",
        "surface-container": "#191f31",
        "on-primary-container": "#00422b",
        "inverse-surface": "#dce1fb",
        "inverse-on-surface": "#2a3043",
        "on-secondary-container": "#adb4ce",
        "on-secondary-fixed": "#131b2e",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-container": "#2e394c",
        secondary: "#bec6e0",
        "surface-container-lowest": "#070d1f",
        "surface-dim": "#0c1324",
        "surface-container-low": "#151b2d",
        "on-primary": "#003824",
        "on-tertiary-fixed": "#111c2d",
        "surface-bright": "#33394c",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#3c475a",
        "outline-variant": "#3c4a42",
        "tertiary-container": "#98a3ba",
        background: "#0c1324",
        "on-secondary": "#283044",
        "surface-container-high": "#23293c",
        "secondary-fixed-dim": "#bec6e0",
        tertiary: "#bcc7de",
        "surface-container-highest": "#2e3447",
        error: "#ffb4ab",
        "primary-container": "#10b981",
        surface: "#0c1324",
        "on-secondary-fixed-variant": "#3f465c",
        primary: "#4edea3",
        "tertiary-fixed-dim": "#bcc7de",
        "error-container": "#93000a",
        "on-primary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "on-surface": "#dce1fb",
        "inverse-primary": "#006c49",
        "on-surface-variant": "#bbcabf",
        "surface-variant": "#2e3447",
        "on-background": "#dce1fb",
      },
      spacing: {
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        lg: "24px",
        xs: "4px",
        xl: "32px",
        unit: "4px",
        md: "16px",
        sm: "8px",
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
