// TFS Aesthetic Reskin - SCRUM-602
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#CC0000",
        secondary: "#1C2B3A",
        accent: "#2563EB",
        success: "#16A34A",
        warning: "#D97706",
        error: "#DC2626",
        "page-background": "#F8FAFC",
        "card-background": "#FFFFFF",
        "text-primary": "#111827",
        "text-secondary": "#6B7280",
        border: "#E5E7EB",
        "focus-ring": "#CC0000",

        // Backward compatibility mappings for existing components
        background: "#F8FAFC",
        surface: "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F8FAFC",
        "surface-container": "#E5E7EB",
        "surface-container-high": "#E5E7EB",
        "surface-container-highest": "#E5E7EB",
        outline: "#6B7280",
        "outline-variant": "#E5E7EB",
        "on-surface": "#111827",
        "on-surface-variant": "#6B7280",
        "secondary-container": "#1C2B3A",
        "on-secondary-container": "#FFFFFF",
        "on-primary": "#FFFFFF",
        "primary-fixed": "#CC0000",
        "on-primary-fixed": "#FFFFFF",
        "tertiary-container": "#2563EB",
        "on-tertiary-container": "#FFFFFF",
        "error-container": "#DC2626",
        "on-error-container": "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-xs": "4px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-lg": "24px",
        "container-max": "1440px",
        gutter: "24px",
        "stack-md": "16px",
        "stack-xl": "48px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        display: ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        display: [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
