/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#7e5700",
        "on-primary-fixed-variant": "#604100",
        "outline-variant": "#d6c4ac",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d6e0f3",
        "on-secondary-container": "#596373",
        "surface-variant": "#e1e2e4",
        "on-error": "#ffffff",
        "on-tertiary-container": "#46505e",
        error: "#ba1a1a",
        "on-surface-variant": "#514532",
        "surface-container-low": "#f3f4f6",
        secondary: "#555f6f",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#7e5700",
        "on-primary-fixed": "#281900",
        "primary-fixed-dim": "#ffba38",
        "tertiary-fixed-dim": "#bdc7d8",
        "surface-bright": "#f8f9fb",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeef0",
        "on-secondary-fixed": "#121c2a",
        outline: "#847560",
        surface: "#f8f9fb",
        "tertiary-fixed": "#d9e3f4",
        background: "#f8f9fb",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#3d4756",
        "surface-dim": "#d9dadc",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bdc7d9",
        "tertiary-container": "#b8c2d3",
        "inverse-on-surface": "#f0f1f3",
        "on-primary-container": "#6b4900",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#3e4755",
        "inverse-primary": "#ffba38",
        "surface-container-high": "#e7e8ea",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdeac",
        tertiary: "#555f6d",
        "primary-container": "#ffb300",
        "on-tertiary-fixed": "#121c28",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d9e3f6",
        "surface-container-highest": "#e1e2e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        md: "16px",
        xs: "4px",
        sm: "8px",
        base: "4px",
        gutter: "20px",
        "container-max": "1440px",
        margin: "24px",
        xl: "32px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg-mobile": ["Work Sans"],
        "headline-sm": ["Work Sans"],
        "display-lg": ["Work Sans"],
        "headline-md": ["Work Sans"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Work Sans"],
        "label-md": ["JetBrains Mono"],
      },
    },
  },
  plugins: [],
};
