/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002113",
        "primary-container": "#007bb9",
        "on-secondary": "#ffffff",
        surface: "#f8f9ff",
        "on-primary-container": "#fdfcff",
        "surface-container": "#e5eeff",
        "inverse-primary": "#93ccff",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#bec6e0",
        "outline-variant": "#bfc7d2",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#3f4850",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#5c647a",
        background: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#cbdbf5",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        "tertiary-container": "#00855b",
        "secondary-container": "#dae2fd",
        "tertiary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#f5fff6",
        tertiary: "#006947",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#001d31",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#004b73",
        "tertiary-fixed": "#6ffbbe",
        primary: "#006194",
        "surface-container-highest": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        secondary: "#565e74",
        "primary-fixed": "#cce5ff",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#131b2e",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#93ccff",
        "secondary-fixed": "#dae2fd",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006398",
        "on-tertiary-fixed-variant": "#005236",
        outline: "#707881",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-xs": "4px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-lg": "24px",
        "container-max": "1440px",
        gutter: "24px",
        "stack-md": "16px",
        "stack-xl": "48px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        display: ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        display: [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
